//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOW.Web.DataModel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public int LanguageID { get; set; }
        public Nullable<bool> MobileNumberConfirmed { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<System.DateTime> TimeStampRego { get; set; }
        public bool EmailVerified { get; set; }
        public string ExternalID { get; set; }
        public Nullable<int> CustomerRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string DeviceStr { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string ProfilePix { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string PersonalVehicleStr { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<int> JobAlerts { get; set; }
        public Nullable<System.Guid> PasswordRecoveryKey { get; set; }
        public Nullable<int> ContactID { get; set; }
    }
}
